services:
  - type: web
    name: uachbot
    env: docker
    repo: https://github.com/crdev/telegram-bot-help-ua-ch
    region: frankfurt
    branch: test-prod
    healthCheckPath: /healthz
    envVars:
      - key: REDIS_HOST
        fromService:
          name: redis
          type: pserv
          property: host
      - key: REDIS_PORT
        fromService:
          name: redis
          type: pserv
          property: port
      - fromGroup: global
